[package]
name = "wikiwho_rs"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "utils_impls"
harness = false

[profile.bench]
lto = true
codegen-units = 1

[features]
default = [ ]
strict = []
optimized_str = []

[dependencies]
arraydeque = "0.5.1"
blake3 = "1.5.4"
chrono = "0.4.38"
clap = { version = "4.5.18", features = ["derive"] }
compact_str = "0.8.0"
itertools = "0.13.0"
md5 = "0.7.0"
quick-xml = "0.36.2"
rand = "0.8.5"
regex = "1.10.6"
rustc-hash = "2.0.0"
similar = "2.6.0"
string-interner = "0.17.0"
thiserror = "1.0.63"
tracing = "0.1.40"
zstd = "0.13.2"

[dev-dependencies]
criterion = "0.5.1"
rand_xoshiro = "0.6.0"
